config/routes.rb
Rails.application.routes.draw do
  resources :clientes do
      resources :veiculos
  end
  resources :veiculos do
      resources :ordem_servicos
  end 

  root :to => 'clientes#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :veiculos
  has_many :ordem_servicos
  mount_uploader :foto, FotoClienteUploader
end

app/models/ordem_servico.rb
class OrdemServico < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :veiculo
end

app/models/veiculo.rb
class Veiculo < ActiveRecord::Base
  belongs_to :cliente
  has_many :ordem_servicos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :rg, :telefone, :endereco, :sexo, :foto)
    end
end

app/controllers/ordem_servicos_controller.rb
class OrdemServicosController < ApplicationController
  before_filter :set_veiculo, only: [:create, :show, :edit, :update, :destroy]
  before_action :set_ordem_servico, only: [:show, :edit, :update, :destroy]
 
  # GET /ordem_servicos
  # GET /ordem_servicos.json
  def index
    @ordem_servicos = OrdemServico.all
  end

  # GET /ordem_servicos/1
  # GET /ordem_servicos/1.json
  def show
  end

  # GET /ordem_servicos/new
  def new
    @ordem_servico = OrdemServico.new
  end
  def new
      @ordem_servico = OrdemServico.new(veiculo_id: permitted_params[:veiculo_id])
      @veiculo = Veiculo.find(permitted_params[:veiculo_id])
   end
  # GET /ordem_servicos/1/edit
  def edit
  end

  # POST /ordem_servicos
  # POST /ordem_servicos.json
  def create
    @ordem_servico = @veiculo.ordem_servicos.build(permitted_params[:ordem_servico]) 
    if @ordem_servico.save
        redirect_to veiculo_ordem_servico_path(@veiculo, @ordem_servico), notice: 'Ordem de serviço criada com sucesso.' 
      else
        render :new 
     end
  end

  # PATCH/PUT /ordem_servicos/1
  # PATCH/PUT /ordem_servicos/1.json
  def update
      if @ordem_servico.update(permitted_params[:ordem_servico])
        redirect_to veiculo_ordem_servico_path(@veiculo, @ordem_servico), notice: 'Ordem de serviço alterada com sucesso.'
      else
        render :edit
      end
  end

  # DELETE /ordem_servicos/1
  # DELETE /ordem_servicos/1.json
  def destroy
    @ordem_servico.destroy
    respond_to do |format|
      format.html { redirect_to ordem_servicos_url, notice: 'Ordem servico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordem_servico
      @ordem_servico = OrdemServico.find(params[:id])
    end

    def set_veiculo
      @veiculo = Veiculo.find(params[:veiculo_id])
    end
    
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def permitted_params
      params.permit(:cliente_id, :veiculo_id, :id, :ordem_servico => [:numero_os, :orcamento, :pedido, :data_inicio, :data_conclusao, :descricao, :valor])
    end
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_filter :set_cliente, only: [:show,:edit, :update, :create]
  before_action :set_veiculo, only: [:show, :edit, :update, :destroy]

  # GET /veiculos
  # GET /veiculos.json
  def index
    @veiculos = Veiculo.all
  end

  # GET /veiculos/1
  # GET /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  
  def new
      @veiculo = Veiculo.new(cliente_id: permitted_params[:cliente_id])
      @cliente = Cliente.find(permitted_params[:cliente_id])
    end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos
  # POST /veiculos.json
  def create
    @veiculo = @cliente.veiculos.build(permitted_params[:veiculo])    
      if @veiculo.save
        redirect_to cliente_veiculo_path(@cliente, @veiculo) , notice: 'Veículo criado com sucesso.'         
      else
        render :new 
      end   
  end

  # PATCH/PUT /veiculos/1
  # PATCH/PUT /veiculos/1.json
  def update
    if @veiculo.update_attributes(permitted_params[:veiculo])
	    redirect_to cliente_veiculo_path(@cliente, @veiculo) , notice: 'Veículo atualizado com sucesso.'
	  else
	    render :edit
	  end
   end

  # DELETE /veiculos/1
  # DELETE /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: 'Veiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:cliente_id])
    end
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permitted_params
      params.permit(:cliente_id, :id, :veiculo => [:placa, :marca, :modelo])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/ordem_servicos_helper.rb
module OrdemServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
  <div class="form-group">
    <%= f.label :foto, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= image_tag @cliente.foto_url.to_s, class: 'foto' if @cliente.foto? %>
      <%= f.file_field :foto, label: 'Foto', input_html: {accept: ('application/jpg') } %>
     </div>
  </div> 
  <div class="form-group">
    <%= f.label :nome, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cpf, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cpf, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rg, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :rg, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :telefone, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :endereco, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :endereco, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sexo, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.radio_button :sexo, 'Masculino', :checked => true %> Masculino
      <%= f.radio_button :sexo, 'Feminino' %> Feminino
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-default dropdown-toggle", :value => "Salvar" %>
    </div>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<div class="page-header">
  <%= link_to clientes_path, :class => 'btn btn-default dropdown-toggle' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  
  <h1>Editando Cliente</h1>
</div>

<%= render 'form' %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
 <div class="dropdown" style="float: right;">  
   <%= link_to new_cliente_path, :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Cliente
    <% end %>
 </div>
  <h1>Clientes</h1>
</div>


<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover"> 
    <thead>
      <tr>
            <th>Nome</th>
            <th>Cpf</th>
            <th>Rg</th>
            <th>Telefone</th>
            <th>Endereco</th>
            <th>Sexo</th>
	    <th>Foto</th>
     </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @clientes.order(created_at: :desc), :class => "row-table") do |cliente| %>
                <td><%= cliente.nome %></td>
                <td><%= cliente.cpf %></td>
                <td><%= cliente.rg %></td>
                <td><%= cliente.telefone %></td>
                <td><%= cliente.endereco %></td>
                <td><%= cliente.sexo %></td>
		<td><%= cliente.foto_url.to_s %></td>
                <td><%= link_to 'Exibir', cliente %></td>
                               
                         
      <% end %>
    </tbody>
  </table>

 
</div>

app/views/clientes/new.html.erb
<div class="page-header">
  <%= link_to clientes_path, :class => 'btn btn-default dropdown-toggle' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  
  <h1>Criando Cliente</h1>
</div>
<%= render 'form' %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
 <div class="dropdown" style="float: right;">
  <%= link_to clientes_path, :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  <%= link_to edit_cliente_path(@cliente), :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <%= link_to new_cliente_veiculo_path(@cliente), :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Veículo
 <% end %>
</div> 
  <h1>Mostrando Cliente</h1>
</div>

<p>
  <strong>Foto:</strong>
  <%= @cliente.foto_url.to_s %>
</p>
 
<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @cliente.rg %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @cliente.endereco %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @cliente.sexo %>
</p>

</br></br><strong>Lista de Veículos</strong></br></br>
 

<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
                  <th> Placa </th>
                  <th> Marca </th>
                  <th> Modelo </th>
      </tr>
    </thead>

    <tbody>
    
      <%= content_tag_for(:tr, @cliente.veiculos.order(created_at: :desc), :class => "row-table") do |veiculo| %>
              
              <td><%= veiculo.placa %></td>
              <td><%= veiculo.marca %></td> 
              <td><%= veiculo.modelo %></td>
              <td><%= link_to 'Exibir', cliente_veiculo_path(@cliente, veiculo) %></td>
      <% end %>
      
    </tbody>
  </table>

app/views/layouts/_latbar.html.erb
<div id="wrapper">
	<div id="sidebar-wrapper">
  	<ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#" >
           <h4>Menu</h4>
        </a>
      </li>
      
      <li style="font-size: 20px;">
      	<%= link_to ' Cliente', clientes_path,class: "glyphicon glyphicon-home" %>  
      </li>
      
		</ul>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <ul class="nav navbar-pills navbar-left">

         
      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      
      <ul class="nav nav-pills navbar-right">
        
        
      </ul>
   </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OficinaMecanica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "layouts/navbar" %>
  
	<div class="container">
		<div class="row">
			
			<div class="col-md-9">
				<div class="panel-body">
					<%= yield %>	
					<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>
				</div>
			</div>
		</div> <!-- row -->
	</div> <!-- container -->
</body>
</html>

app/views/ordem_servicos/_form.html.erb
  <% if @ordem_servico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ordem_servico.errors.count, "error") %> prohibited this ordem_servico from being saved:</h2>

      <ul>
      <% @ordem_servico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :numero_os, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :numero_os, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :orcamento, :class => "col-sm-2 control-label" %>
    <div class="col-sm-1">
       <%= f.check_box :orcamento, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pedido, :class => "col-sm-2 control-label" %>
    <div class="col-sm-1">
       <%= f.check_box :pedido, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_inicio, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
       <%= f.text_field :data_inicio,  class: 'datepicker'  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_conclusao, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :data_conclusao,  class: 'datepicker'  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descricao, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
       <%= f.text_area :descricao, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => "col-sm-2 control-label" %>
    <div class="col-sm-2">
       <%= f.text_field :valor, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-default dropdown-toggle", :value => "Salvar" %>
    </div>
  </div>
 
<script type= "text/javascript" >  
  $(document).ready(function(){
  $('.datepicker').datepicker({format:'dd-mm-yyyy'});
  $('#matricula').inputmask("9999.9.999.9999");  
  });
</script>   

app/views/ordem_servicos/edit.html.erb
<div class="page-header">
 <%= link_to veiculo_ordem_servico_path(@veiculo, @ordem_servico), :class => 'btn btn-default dropdown-toggle' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  
  <h1>Editando Ordem de Serviço</h1>
</div>
  

<%= form_for(@ordem_servico, url: veiculo_ordem_servico_path(@veiculo, @ordem_servico), :html => { :class => "form-horizontal" }) do |f| %>

  <%= render partial: 'form', locals: {f: f} %>
 
<% end %>

app/views/ordem_servicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ordem Servicos</h1>

<table>
  <thead>
    <tr>
      <th>Numero os</th>
      <th>Orcamento</th>
      <th>Pedido</th>
      <th>Data inicio</th>
      <th>Data conclusao</th>
      <th>Descricao</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordem_servicos.each do |ordem_servico| %>
      <tr>
        <td><%= ordem_servico.numero_os %></td>
        <td><%= ordem_servico.orcamento %></td>
        <td><%= ordem_servico.pedido %></td>
        <td><%= ordem_servico.data_inicio %></td>
        <td><%= ordem_servico.data_conclusao %></td>
        <td><%= ordem_servico.descricao %></td>
        <td><%= ordem_servico.valor %></td>
        <td><%= link_to 'Show', ordem_servico %></td>
        <td><%= link_to 'Edit', edit_ordem_servico_path(ordem_servico) %></td>
        <td><%= link_to 'Destroy', ordem_servico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordem servico', new_ordem_servico_path %>

app/views/ordem_servicos/new.html.erb
<div class="page-header">
 <%= link_to cliente_veiculo_path(@veiculo.cliente, @veiculo), :class => 'btn btn-default dropdown-toggle' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>  
 <h1>Nova Ordem de Serviço</h1>
</div>
  
  

<%= form_for(@ordem_servico, url: veiculo_ordem_servicos_path(@veiculo), :html => { :class => "form-horizontal" }) do |f| %>

  <%= render partial: 'form', locals: {f: f} %>
 
<% end %>

app/views/ordem_servicos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
 <div class="dropdown" style="float: right;">
  <%= link_to cliente_veiculo_path(@veiculo.cliente, @veiculo), :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  <%= link_to edit_veiculo_ordem_servico_path(@veiculo, @ordem_servico), :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
</div> 
  <h1>Mostrando Ordem de Serviço</h1>
</div>
<p>
  <strong>Número da os:</strong>
  <%= @ordem_servico.numero_os %>
</p>

<p>  
  <% if @ordem_servico.orcamento? %>
   <strong>Tipo de OS:</strong> Orçamento
  <% elsif @ordem_servico.pedido? %>  
   <strong>Tipo de OS:</strong> Pedido
  <% end %>
</p>

<p>
  <strong>Data início:</strong>
  <%= @ordem_servico.data_inicio %>
</p>

<p>
  <strong>Data conclusão:</strong>
  <%= @ordem_servico.data_conclusao %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @ordem_servico.descricao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @ordem_servico.valor %>
</p>

app/views/veiculos/_form.html.erb
 <div class="form-group">
    <%= f.label :placa, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :placa, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :marca, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :marca, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :modelo, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :modelo, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-default dropdown-toggle", :value => "Salvar" %>
    </div>
  </div>

app/views/veiculos/edit.html.erb
<div class="page-header">
<div class="page-header">
  <%= link_to cliente_veiculo_path(@cliente, @veiculo), :class => 'btn btn-default dropdown-toggle' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  
  <h1>Editando Veículo</h1>
</div>
  

<%= form_for(@veiculo, url: cliente_veiculo_path(@cliente, @veiculo), :html => { :class => "form-horizontal" }) do |f| %>

  <%= render partial: 'form', locals: {f: f} %>
 
<% end %>

app/views/veiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Veiculos</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veiculos.each do |veiculo| %>
      <tr>
        <td><%= veiculo.placa %></td>
        <td><%= veiculo.marca %></td>
        <td><%= veiculo.modelo %></td>
        <td><%= link_to 'Show', veiculo %></td>
        <td><%= link_to 'Edit', edit_veiculo_path(veiculo) %></td>
        <td><%= link_to 'Destroy', veiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veiculo', new_veiculo_path %>

app/views/veiculos/new.html.erb
<div class="page-header">
<div class="page-header">
  <%= link_to cliente_path(@cliente), :class => 'btn btn-default dropdown-toggle' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  
  <h1>Novo Veículo</h1>
</div> 
  

<%= form_for(@veiculo, url: cliente_veiculos_path(@cliente), :html => { :class => "form-horizontal" }) do |f| %>

  <%= render partial: 'form', locals: {f: f} %>
 
<% end %>

app/views/veiculos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
 <div class="dropdown" style="float: right;">
  <%= link_to cliente_path(@cliente), :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
  <%= link_to edit_cliente_veiculo_path(@cliente, @veiculo), :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <%= link_to new_veiculo_ordem_servico_path(@veiculo), :class => "btn btn-default dropdown-toggle" do %>
    <span class="glyphicon glyphicon-alt"></span>
    Abrir Ordem de Serviço
  <% end %>
</div> 
  <h1>Mostrando Veículo</h1>
</div>


<p>
  <strong>Placa:</strong>
  <%= @veiculo.placa %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @veiculo.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @veiculo.modelo %>
</p>

</br></br><strong>Lista de Veículos</strong></br></br>
 

<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
                  <th> Número da OS </th>
                  <th> Tipo de Ordem </th>
                  <th> Placa do veículo </th>
      </tr>
    </thead>

    <tbody>
    
      <%= content_tag_for(:tr, @veiculo.ordem_servicos.order(created_at: :desc), :class => "row-table") do |ordem_servico| %>
              
              <td><%= ordem_servico.numero_os %></td>
              <% if ordem_servico.orcamento? %>
                <td>Orçamento</td>
              <% elsif ordem_servico.pedido? %>  
                <td>Pedido</td> 
              <% end %>
              <td><%= @veiculo.placa %></td>
              <td><%= link_to 'Mostrar', veiculo_ordem_servico_path(@veiculo, ordem_servico) %></td>
      <% end %>
      
    </tbody>
  </table>